version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5932:5432'
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_name
      POSTGRES_HOST_AUTH_METHOD: trust